name: check-if-container-exists

on:
  push:
    branches: [azure-test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Container
        uses: azure/cli@v1.0.0
        with:
          inlineScript: |
           az storage container exists --account-name aottergeneral --sas-token '${{ secrets.AZURE_STORAGE_SAS_TOKEN }}' --name sdk --dedug
