# This is a basic workflow to help you get started with Actions
name: Check If Container Exists

# Controls when the workflow will run
on:
  push:
    branches: [ azure-test ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Container
        uses: azure/cli@v1.0.0
        with:
          inlineScript: |
           az storage container exists --name sdk --account-name aottergeneral --sas-token ${{ secrets.AZURE_STORAGE_SAS_TOKEN }} 
